#!/bin/sh

info=$(cat << EOF
clnv list-funds

visualizer for listfunds or listmempoolfunds if the plugin is present
EOF
)

if [ "$#" -ge 1 ]; then
    case "$1" in
        -h|--help)
            echo "$info"
            exit 0
        ;;
    esac
fi

msat_to_sat() {
    msat="$(cat)"
    echo "$msat / (10 ^ 3)" | bc
}

if $CLN_BIN plugin list 2>/dev/null | grep -F listmempoolfunds >/dev/null 2>&1; then
    action="listmempoolfunds"
else
    action="listfunds"
fi

$CLN_BIN "$action" |
jq -r '.outputs[] | "\(.txid) \(.output) \(.amount_msat) \(.address) \(.status) \(.blockheight)"' |
while read -r line; do
    txid="$(printf "%s\n" "$line" | cut -d " " -f 1)"
    output="$(printf "%s\n" "$line" | cut -d " " -f 2)"
    amount_msat="$(printf "%s\n" "$line" | cut -d " " -f 3)"
    address="$(printf "%s\n" "$line" | cut -d " " -f 4)"
    status="$(printf "%s\n" "$line" | cut -d " " -f 5)"
    blockheight="$(printf "%s\n" "$line" | cut -d " " -f 6)"

    sat="$(printf "%s\n" "$amount_msat" | cut -d "m" -f 1 | msat_to_sat)"

    printf "%-64s %4s %12s %-62s %7s %-11s\n" \
        "$txid" "$output" "$sat" "$address" "$blockheight" "$status"
done
