#!/bin/sh

info=$(cat << EOF
clnv search search-element

search in listpays and listinvoices
EOF
)

if [ "$#" -lt 1 ]; then
    echo "error: insert search element" >&2
    exit 1
fi
search="$1"
shift 1

case "$search" in
    -h|--help)
        echo "$info"
        exit 0
    ;;
esac

jq_search_any() {
    cat << EOF
.${1} |= map(select(any(.[]; tostring | contains("${2}"))))
EOF
}

pays_found="$(
    $CLN_BIN listpays |
    jq -r "$(jq_search_any "pays" "$search")"
)"
pays_found_len="$(
    printf "%s\n" "$pays_found" |
    jq -r ".pays | length"
)"
if [ "$pays_found_len" -gt 0 ]; then
    printf "%s\n" "$pays_found" |
    "$CLNV_HOME/scripts/clnv-list-pays"
fi

invoices_found="$(
    $CLN_BIN listinvoices |
    jq -r "$(jq_search_any "invoices" "$search")"
)"
invoices_found_len="$(
    printf "%s\n" "$invoices_found" |
    jq -r ".invoices | length"
)"
if [ "$invoices_found_len" -gt 0 ]; then
    printf "%s\n" "$invoices_found" |
    "$CLNV_HOME/scripts/clnv-list-invoices"
fi

if [ "$pays_found_len" -eq 0 ] && [ "$invoices_found_len" -eq 0 ]; then
    exit 1
fi

exit 0
